services:
  db: # the service hosting your MySQL instance
    image: mysql:5.7 # the image and tag docker will pull from docker hub
    container_name: dev_db
    volumes: # this section allows you to configure persistence within multiple restarts
      - db_data:/var/lib/mysql
    restart: always # if the db crash somehow, restart it
    environment: # env variables, you usually set this to override existing ones
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - backend

  api:
    container_name: dev_api
    # image: sample-express-app
    build: .
    restart: unless-stopped
    environment:
      DB_HOST: db
    # ports:
    #   - "3001:3000"
    networks:
      - backend
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.rule=Host(`apiclo901.musubi.dev`)"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.api.loadbalancer.server.port=3000"

networks:
  backend:
    driver: bridge
  traefik:
    external: true
    name: traefik
volumes:
  db_data: