services:
  front:
    build: .
    # ports:
    #   - 8080:80
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.rule=Host(`appclo901.musubi.dev`)"
      - "traefik.http.routers.front.tls=true"
      - "traefik.http.routers.front.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.front.loadbalancer.server.port=80"

networks:
  traefik:
    external: true
    name: traefik
